image: 'docker:latest'

services:
  - docker:17.09.0-dind

stages:
  - build

Build and Publish:
  stage: build
  before_script:
    - 'docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS'
  script:
    - docker build -t "$DOCKERHUB_USER/hugo_builder:v$CI_COMMIT_TAG" --build-arg "HUGOVERSION=$CI_COMMIT_TAG" .
    - docker push "$DOCKERHUB_USER/hugo_builder:v$CI_COMMIT_TAG"
  only:
    - tags
