language: generic

services:
  - docker

env:
  - PROJECT_IMAGE=ncatelli/hugo_builder

script:
  - docker build -t $PROJECT_IMAGE:$TRAVIS_BRANCH -t $PROJECT_IMAGE:latest .

deploy:
  if: TRAVIS_PULL_REQUEST = false
  provider: script
  script: 
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push $PROJECT_IMAGE:latest
    - docker push $PROJECT_IMAGE:$TRAVIS_BRANCH
  on:
    branch: master
